# Generated by Django 5.1.2 on 2024-11-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.IntegerField()),
                ('prod_exp', models.DateField()),
                ('prod_quantity', models.IntegerField()),
                ('prod_manufacture', models.DateField()),
                ('prod_description', models.CharField(max_length=100)),
                ('prod_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
